#!/bin/bash

if [ "$#" -ne 1  ]; then
	echo "Wrong number of arguments."
	$SHELL
	exit 1
fi

if [ -f $1 ]; then
	
	imageformat=$(basename $1 | cut -d "." -f 2)
	if [ $imageformat != "jpg" ]; then
		echo "$imageformat - unsupported image format. This script only uses .jpg images."
		$SHELL
		exit 1
	fi

	cp $1 $HOME/
	imagename=$(basename $1)
	
	if [ -f $HOME/wallpaper_prev.jpg ]; then
		rm $HOME/wallpaper_prev.jpg
		echo "Deleting previous wallpaper."
	fi
	
	if [ -f $HOME/wallpaper.jpg ]; then
		mv $HOME/wallpaper.jpg $HOME/wallpaper_prev.jpg
	fi
	
	mv $HOME/$imagename $HOME/wallpaper.jpg
	echo "The new wallpaper file has been moved."
	echo "Using wal -t -i $HOME/wallpaper.jpg to apply."
	wal -c
	wal -t -i $HOME/wallpaper.jpg
	notify-send Wallpaper "Wallpaper set to $imagename"
else
	echo "Image file not found."
fi
$SHELL
